### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by qingbolove** [adjust/smart_banner_sdk#16]
![image](https://github.com/adjust/smart_banner_sdk/assets/10628904/75859cc9-5b86-4aa3-8b2b-94ef279325cf)
When I integrate the sdk using the documents, I encounter an issue that self is not defined, I cannot proceed anymore, please help

**Comment by YaraMatkova** [comment]
Hi @qingbolove, thank you for reaching out.

Could you please share more details? What framework do you use?

**Comment by qingbolove** [comment]
this is because we are using nextjs, smart banner sdk do not support nextjs ssr mode, we need to use it this way: AdjustSmartBanner = (await import('@adjustcom/smart-banner-sdk')).default;
