### ISSUE TITLE
Calling show appends invisible Banners

### ISSUE THREAD

**Issue by msienkiewicz7** [adjust/smart_banner_sdk#4]
The [docs](https://github.com/adjust/smart_banner_sdk#show) say:
> If your web application is a single page application (SPA) you should call this method after navigation happens

Whenever I call `AdjustSmartBanner.show();` on navigation end there is a new hidden Smart Banner element appended to the DOM.

**Comment by YaraMatkova** [comment]
Hi @msienkiewicz7, thank you for getting in touch, and please excuse me for such long delay.

I believe this issue was fixed, so I'm closing this now.

Feel free to reopen if the issue still persists or if you have any further questions.

Have a great day!
